### PR TITLE
Fix recipe before 23.9 release

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
## Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR is based on #49. I updated the build number this time to fix the recipe in anticipation of the 23.9 release on PyPI, this build number can be reset to 0 thereupon (https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-recipes). I will run conda-smithy here since the CI configuration will need an update due to a change in the Python selectors (https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks). Since the version is not being bumped, this should be the recommended way to update the recipe (it won't upload the package this way), IIUC.

For more details, check https://github.com/pybamm-team/PyBaMM/issues/3442

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
@conda-forge-admin, please rerender

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @agriyakhetarpal! This looks good!

I misunderstood your previous PR. I thought you were trying to fix the next release, but I see you were fixing the previous release. This should also close the conda-forge issue in PyBaMM's repo.

**Comment by agriyakhetarpal** [comment]
Yes, I was trying to fix `23.5`, though this will fix the next conda-forge release too ahead of when `23.9` is available to PyPI! The next automated PR will have the correct Python version selectors due to the changes here. Let me know if I should go ahead and merge this, I will add a note in the PyBaMM issue thread about this and close that one afterwards (I don't think it is currently possible to close issues with PRs when both of them are in different repositories or organisations haha)

**Comment by Saransh-cpp** [comment]
Sounds good! I think it would be safe to merge this.

**Pull request merged**
