### PR TITLE
Updates for 23.9 release

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
@conda-forge-admin, please rerender

**Comment by agriyakhetarpal** [comment]
The build pipelines failed here, based on the logs I am assuming that they should be triggered again after 23.9 is out on PyPI. Or should we start making a `conda-forge` release for release candidates as well? (cc: @brosaplanella @Saransh-cpp)

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]
feedstocks are not usually updated with manual PRs, instead, fixes must be pushed to the automated release PR before it is merged.

I'll suggest looking at older version bump PRs (from the conda-forge bot) in this or other feedstocks to get an idea about how fixes are made.

I'll suggest closing this and pushing commits to the automated PR (once it is created - once v23.9 is tagged on PyPI).

> Or should we start making a conda-forge release for release candidates as well

conda-forge releases are automatic and they are triggered by the releases on PyPI.

**Comment by Saransh-cpp** [comment]
I see, my review is not blocking this PR from merging because I'm not a maintainer. Feel free to add me, I'll be happy to review PRs (or make fixes)!

**Comment by agriyakhetarpal** [comment]
> conda-forge releases are automatic and they are triggered by the releases on PyPI.

Yes, however the PyPI _pre_-release versions are not found by the conda-forge-autotick-bot and hence there is no subsequent build on this feedstock. If we want to create a conda pre-release, we need to do that manually (https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds).

> I'll suggest closing this and pushing commits to the automated PR

That sounds like a cleaner solution, closing this. Let me see if I have the appropriate permissions to add you as a maintainer here

**Comment by agriyakhetarpal** [comment]
I can see you as a CODEOWNER now, looks like it worked ✅

**Comment by agriyakhetarpal** [comment]
Also, I think it should be fine to update the recipe as I was doing here. I just needed to update the build number so that an updated version is not shipped (https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-recipes). I will open a new PR for this

**Pull request closed without merging**
